### ISSUE TITLE
NPE target validate

### ISSUE THREAD

**Issue by andrejpetras** [lorislab/mechanic#1]
ERROR] !!! Error executing the mechanic tool.
java.lang.NullPointerException
        at org.lorislab.mechanic.targets.ValidateTarget.processChanges(ValidateTarget.java:56)
        at org.lorislab.mechanic.targets.AbstractUpdateTarget.execute(AbstractUpdateTarget.java:86)
        at org.lorislab.mechanic.app.MechanicApplication.run(MechanicApplication.java:300)
        at org.lorislab.mechanic.Main.lambda$main$0(Main.java:63)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.lorislab.mechanic.Main.main(Main.java:61)

**Comment by andrejpetras** [comment]
Improve valiation of the template properties and configuration properties.
